"""initial schema

Revision ID: b0b9c6b12587
Revises: 
Create Date: 2026-09-10 02:54:43.183404

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b0b9c6b12587'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_dogs_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dogs'))
    )
    op.create_index(op.f('ix_dogs_owner_id'), 'dogs', ['owner_id'], unique=False)
    op.create_index('ix_dogs_owner_id_name', 'dogs', ['owner_id', 'name'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('media_metadata', sa.JSON(), nullable=True),
    sa.Column('storage_reference', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_assets_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index('ix_media_assets_owner_created', 'media_assets', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_id'), 'media_assets', ['owner_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dog_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], name=op.f('fk_analyses_dog_id_dogs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index('ix_analyses_dog_created', 'analyses', ['dog_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_idempotency_key'), 'analyses', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_index('ix_analyses_status_created', 'analyses', ['status', 'created_at'], unique=False)
    op.create_index('ix_analyses_user_created', 'analyses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('analysis_context',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('owner_presence', sa.String(length=20), nullable=True),
    sa.Column('activity_state', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('recent_feeding', sa.Boolean(), nullable=True),
    sa.Column('recent_walk', sa.Boolean(), nullable=True),
    sa.Column('recent_play', sa.Boolean(), nullable=True),
    sa.Column('presence_of_strangers', sa.Boolean(), nullable=True),
    sa.Column('presence_of_other_animals', sa.Boolean(), nullable=True),
    sa.Column('recent_stressful_event', sa.Boolean(), nullable=True),
    sa.Column('location_category', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_context_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_context'))
    )
    op.create_index(op.f('ix_analysis_context_analysis_id'), 'analysis_context', ['analysis_id'], unique=True)
    op.create_table('analysis_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('predicted_behavior', sa.String(length=40), nullable=True),
    sa.Column('corrected_behavior', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_feedback_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analysis_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_feedback'))
    )
    op.create_index(op.f('ix_analysis_feedback_analysis_id'), 'analysis_feedback', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_feedback_user_id'), 'analysis_feedback', ['user_id'], unique=False)
    op.create_table('analysis_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('media_metadata', sa.JSON(), nullable=True),
    sa.Column('storage_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_media_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], name=op.f('fk_analysis_media_asset_id_media_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_analysis_media_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_media'))
    )
    op.create_index(op.f('ix_analysis_media_analysis_id'), 'analysis_media', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_media_asset_id'), 'analysis_media', ['asset_id'], unique=False)
    op.create_index(op.f('ix_analysis_media_owner_id'), 'analysis_media', ['owner_id'], unique=False)
    op.create_table('analysis_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_observations_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_observations'))
    )
    op.create_index(op.f('ix_analysis_observations_analysis_id'), 'analysis_observations', ['analysis_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('primary_behavior', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('secondary_behaviors', sa.JSON(), nullable=False),
    sa.Column('detected_audio_category', sa.String(length=20), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_results_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    op.create_index(op.f('ix_analysis_results_analysis_id'), 'analysis_results', ['analysis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables are dropped directly: dropping a table also drops its indexes and
    # foreign-key constraints on every supported backend. On MySQL/MariaDB an
    # index backing a foreign key cannot be dropped while the constraint still
    # references it, so explicit drop_index calls would fail there.
    op.drop_table('analysis_results')
    op.drop_table('analysis_observations')
    op.drop_table('analysis_media')
    op.drop_table('analysis_feedback')
    op.drop_table('analysis_context')
    op.drop_table('analyses')
    op.drop_table('media_assets')
    op.drop_table('dogs')
    op.drop_table('users')
    # ### end Alembic commands ###
